apiVersion: v1
kind: Service
metadata:
  name: {{ include "1sec.fullname" . }}
  labels:
    {{- include "1sec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.natsPort }}
      targetPort: nats
      protocol: TCP
      name: nats
    - port: {{ .Values.service.syslogPort }}
      targetPort: syslog-udp
      protocol: UDP
      name: syslog-udp
    - port: {{ .Values.service.syslogPort }}
      targetPort: syslog-tcp
      protocol: TCP
      name: syslog-tcp
  selector:
    {{- include "1sec.selectorLabels" . | nindent 4 }}
